### ISSUE TITLE
Screen for all known illumina adapters

### ISSUE THREAD

**Issue by ewels** [remiolsen/anglerfish#7]
It would be nice to be able to supply a file of all known illumina indexes to screen for unexpected contamination, even for low level pool contamination.

**Comment by remiolsen** [comment]
Suggestion after discussing this with @FranBonath is to do a count of barcodes using the same mapping procedure that already exists, with the following rules:

1. Only use perfectly mapping barcodes (i.e. no indels)
2. Exclude i5+i7 barcodes found in the samplesheet
3. Output a list of 100 (500?) most abundant barcodes found

At first, use only the library constructs that are in the samplesheet. For instance single-index 8bp separately, from dual index 8+8 and so on. And not look for unknown library constructs, since this might be in conflict with rules 1 and 2.
